apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Release.Name }}-allow-source-controller-traffic
  namespace: {{ .Release.Namespace }}
spec:
  egress:
    - {}
  podSelector:
    matchLabels:
      app: source-controller
  policyTypes:
    - Egress
