{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledResources:
        - cpu
        - memory
      minAllowed:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.limits.cpu }}
        memory: {{ .Values.resources.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: Auto
{{ end }}
