version: 2.1
orbs:
  architect: giantswarm/architect@5.13.1

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: konfigure-operator
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: push-to-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: konfigure-operator
        # This is needed for `architect/run-tests-with-ats` to work
        persist_chart_archive: true
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    - architect/run-tests-with-ats:
        name: ats-functional-tests
        additional_app-test-suite_flags: "--functional-tests-cluster-type kind --test-executor pytest --skip-steps smoke upgrade"
        app-test-suite_version: "v0.10.3"
        app-test-suite_container_tag: "0.10.3"
        filters:
          branches:
            ignore:
              - main
        requires:
          - push-to-app-catalog

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capa-app-collection
        app_name: konfigure-operator
        app_collection_repo: capa-app-collection
        requires:
          - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capz-app-collection
        app_name: konfigure-operator
        app_collection_repo: capz-app-collection
        requires:
          - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-vsphere-app-collection
        app_name: konfigure-operator
        app_collection_repo: vsphere-app-collection
        requires:
          - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/


    - architect/push-to-app-collection:
        name: push-to-cloud-director-app-collection
        context: architect
        app_name: konfigure-operator
        app_collection_repo: cloud-director-app-collection
        requires:
          - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-proxmox-app-collection
        app_name: konfigure-operator
        app_collection_repo: proxmox-app-collection
        requires:
          - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
