# This rule is not used by the project konfigure-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the konfigure.giantswarm.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: konfigure-operator
    app.kubernetes.io/managed-by: kustomize
  name: konfigurationschema-editor-role
rules:
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurationschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurationschemas/status
  verbs:
  - get
