# permissions for end users to view managementclusterconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: konfigure-operator
    app.kubernetes.io/managed-by: kustomize
  name: managementclusterconfiguration-viewer-role
rules:
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - managementclusterconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - managementclusterconfigurations/status
  verbs:
  - get
