---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurations/status
  verbs:
  - get
  - patch
  - update
