image:
  registry: gsoci.azurecr.io
  name: "giantswarm/konfigure-operator"
  tag: ""

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Vertical pod autoscaler
verticalPodAutoscaler:
  enabled: false

# Pod securityContext
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
