# Deployment
image:
  registry: gsoci.azurecr.io
  name: "giantswarm/konfigure-operator"
  tag: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

volumes:
  cache:
    sizeLimit: 32Mi
  sopsenv:
    sizeLimit: 2Mi
  temp:
    sizeLimit: 4Mi

# Vertical pod autoscaler
verticalPodAutoscaler:
  enabled: false

# Pod securityContext
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Prometheus
metrics:
  podMonitor:
    enabled: true
    interval: "60s"
    scrapeTimeout: "45s"
