apiVersion: konfigure.giantswarm.io/v1alpha1
kind: Konfiguration
metadata:
  name: konfiguration-sample
  namespace: default
spec:
  targets:
    schema:
      reference:
        name: konfigurationschema-sample
        namespace: default
    defaults:
      variables:
        - name: installation
          value: golem
    iterations:
      app-operator:
        variables:
          - name: app
            value: app-operator
      chart-operator:
        variables:
          - name: app
            value: chart-operator
      dex-operator:
        variables:
          - name: app
            value: dex-operator
  destination:
    namespace: default
    naming:
      suffix: sample
  reconciliation:
    interval: 1m
    retryInterval: 10s
  sources:
    flux:
      gitRepository:
        name: config-sample
        namespace: default
