apiVersion: konfigure.giantswarm.io/v1alpha1
kind: ManagementClusterConfiguration
metadata:
  name: example-3
  namespace: konfigure-operator-system
spec:
  configuration:
    applications:
      includes:
        exactMatchers:
          - app-operator
          - chart-operator
        regexMatchers: []
      excludes:
        exactMatchers: []
        regexMatchers: []
    cluster:
      name: golem
  destination:
    namespace: default
    naming:
      prefix: zz
      suffix: x-y-z
  reconciliation:
    interval: 1m
    retryInterval: 30s
  sources:
    flux:
      gitRepository:
        name: "giantswarm-config"
        namespace: "flux-giantswarm"
      service:
        url: "source-controller.flux-giantswarm.svc"
