apiVersion: konfigure.giantswarm.io/v1alpha1
kind: ManagementClusterConfiguration
metadata:
  name: example-5
  namespace: konfigure-operator-system
spec:
  configuration:
    applications:
      includes:
        exactMatchers:
          - app-operator
          - chart-operator
        regexMatchers: []
      excludes:
        exactMatchers: []
        regexMatchers: []
    cluster:
      name: golem
  destination:
    namespace: default
    naming:
      prefix: pre
      suffix: post
      useSeparator: false
  reconciliation:
    interval: 1m
  sources:
    flux:
      gitRepository:
        name: "giantswarm-config"
        namespace: "flux-giantswarm"
      service:
        url: "asd.qwe.svc"
