apiVersion: konfigure.giantswarm.io/v1alpha1
kind: ManagementClusterConfiguration
metadata:
  name: example-1
  namespace: konfigure-operator-system
spec:
  configuration:
    applications:
      includes:
        exactMatchers:
          - app-operator
          - chart-operator
        regexMatchers: []
      excludes:
        exactMatchers: []
        regexMatchers: []
    cluster:
      name: golem
  destination:
    namespace: default
    naming:
      suffix: laszlo
  reconciliation:
    interval: 1m
    retryInterval: 10s
  sources:
    flux:
      gitRepository:
        name: "giantswarm-config"
        namespace: "flux-giantswarm"
