apiVersion: konfigure.giantswarm.io/v1alpha1
kind: KonfigurationSchema
metadata:
  labels:
    app.kubernetes.io/name: konfigure-operator
    app.kubernetes.io/managed-by: kustomize
  name: konfigurationschema-sample
spec:
  raw: |-
    variables:
      - name: installation
        required: true
      - name: app
        required: true
    layers:
      - id: defaults
        path:
          directory: default
          required: true
        values:
          path:
            directory: ""
          configMap:
            name: config.yaml
            required: true
        templates:
          path:
            directory: apps/<< app >>
            required: true
          configMap:
            name: configmap-values.yaml.template
            required: true
            values:
              merge:
                strategy: ConfigMapsInLayerOrder
          secret:
            name: secret-values.yaml.template
            required: false
            values:
              merge:
                strategy: ConfigMapsAndSecretsInLayerOrder
      - id: management-cluster
        path:
          directory: installations/<< installation >>
          required: true
        values:
          path:
            directory: ""
          configMap:
            name: config.yaml.patch
            required: true
          secret:
            name: secret.yaml
            required: true
        templates:
          path:
            directory: apps/<< app >>
            required: false
          configMap:
            name: configmap-values.yaml.patch
            required: false
            values:
              merge:
                strategy: ConfigMapsInLayerOrder
          secret:
            name: secret-values.yaml.patch
            required: false
            values:
              merge:
                strategy: SameTypeFromCurrentLayer
    includes:
      - id: include
        function:
          name: include
        path:
          directory: include
          required: true # unused
        extension: .yaml.template
      - id: include-self
        function:
          name: includeSelf
        path:
          directory: include-self
          required: false # unused
        extension: .yaml.template
