apiVersion: konfigure.giantswarm.io/v1alpha1
kind: KonfigurationSchema
metadata:
  labels:
    app.kubernetes.io/name: konfigure-operator
    app.kubernetes.io/managed-by: kustomize
  name: konfigurationschema-sample
spec:
  raw:
    remote:
      url: https://raw.githubusercontent.com/giantswarm/konfiguration-schemas/refs/heads/main/schemas/management-cluster-configuration/schema.yaml
