//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationMatchers) DeepCopyInto(out *ApplicationMatchers) {
	*out = *in
	if in.ExactMatchers != nil {
		in, out := &in.ExactMatchers, &out.ExactMatchers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegexMatchers != nil {
		in, out := &in.RegexMatchers, &out.RegexMatchers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationMatchers.
func (in *ApplicationMatchers) DeepCopy() *ApplicationMatchers {
	if in == nil {
		return nil
	}
	out := new(ApplicationMatchers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationsConfiguration) DeepCopyInto(out *ApplicationsConfiguration) {
	*out = *in
	in.Includes.DeepCopyInto(&out.Includes)
	in.Excludes.DeepCopyInto(&out.Excludes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationsConfiguration.
func (in *ApplicationsConfiguration) DeepCopy() *ApplicationsConfiguration {
	if in == nil {
		return nil
	}
	out := new(ApplicationsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfiguration) DeepCopyInto(out *ClusterConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfiguration.
func (in *ClusterConfiguration) DeepCopy() *ClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.Cluster = in.Cluster
	in.Applications.DeepCopyInto(&out.Applications)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Destination) DeepCopyInto(out *Destination) {
	*out = *in
	out.Naming = in.Naming
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Destination.
func (in *Destination) DeepCopy() *Destination {
	if in == nil {
		return nil
	}
	out := new(Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisabledReconcile) DeepCopyInto(out *DisabledReconcile) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisabledReconcile.
func (in *DisabledReconcile) DeepCopy() *DisabledReconcile {
	if in == nil {
		return nil
	}
	out := new(DisabledReconcile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisabledReconcileTarget) DeepCopyInto(out *DisabledReconcileTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisabledReconcileTarget.
func (in *DisabledReconcileTarget) DeepCopy() *DisabledReconcileTarget {
	if in == nil {
		return nil
	}
	out := new(DisabledReconcileTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureStatus) DeepCopyInto(out *FailureStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureStatus.
func (in *FailureStatus) DeepCopy() *FailureStatus {
	if in == nil {
		return nil
	}
	out := new(FailureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxSource) DeepCopyInto(out *FluxSource) {
	*out = *in
	out.Service = in.Service
	out.GitRepository = in.GitRepository
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxSource.
func (in *FluxSource) DeepCopy() *FluxSource {
	if in == nil {
		return nil
	}
	out := new(FluxSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxSourceGitRepository) DeepCopyInto(out *FluxSourceGitRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxSourceGitRepository.
func (in *FluxSourceGitRepository) DeepCopy() *FluxSourceGitRepository {
	if in == nil {
		return nil
	}
	out := new(FluxSourceGitRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxSourceService) DeepCopyInto(out *FluxSourceService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxSourceService.
func (in *FluxSourceService) DeepCopy() *FluxSourceService {
	if in == nil {
		return nil
	}
	out := new(FluxSourceService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfiguration) DeepCopyInto(out *ManagementClusterConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfiguration.
func (in *ManagementClusterConfiguration) DeepCopy() *ManagementClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfigurationList) DeepCopyInto(out *ManagementClusterConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementClusterConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfigurationList.
func (in *ManagementClusterConfigurationList) DeepCopy() *ManagementClusterConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfigurationSpec) DeepCopyInto(out *ManagementClusterConfigurationSpec) {
	*out = *in
	out.Sources = in.Sources
	out.Destination = in.Destination
	in.Configuration.DeepCopyInto(&out.Configuration)
	in.Reconciliation.DeepCopyInto(&out.Reconciliation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfigurationSpec.
func (in *ManagementClusterConfigurationSpec) DeepCopy() *ManagementClusterConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfigurationStatus) DeepCopyInto(out *ManagementClusterConfigurationStatus) {
	*out = *in
	if in.Failures != nil {
		in, out := &in.Failures, &out.Failures
		*out = make([]FailureStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Misses != nil {
		in, out := &in.Misses, &out.Misses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisabledReconciles != nil {
		in, out := &in.DisabledReconciles, &out.DisabledReconciles
		*out = make([]DisabledReconcile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfigurationStatus.
func (in *ManagementClusterConfigurationStatus) DeepCopy() *ManagementClusterConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamingOptions) DeepCopyInto(out *NamingOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamingOptions.
func (in *NamingOptions) DeepCopy() *NamingOptions {
	if in == nil {
		return nil
	}
	out := new(NamingOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reconciliation) DeepCopyInto(out *Reconciliation) {
	*out = *in
	out.Interval = in.Interval
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reconciliation.
func (in *Reconciliation) DeepCopy() *Reconciliation {
	if in == nil {
		return nil
	}
	out := new(Reconciliation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sources) DeepCopyInto(out *Sources) {
	*out = *in
	out.Flux = in.Flux
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sources.
func (in *Sources) DeepCopy() *Sources {
	if in == nil {
		return nil
	}
	out := new(Sources)
	in.DeepCopyInto(out)
	return out
}
