//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationMatchers) DeepCopyInto(out *ApplicationMatchers) {
	*out = *in
	if in.ExactMatchers != nil {
		in, out := &in.ExactMatchers, &out.ExactMatchers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegexMatchers != nil {
		in, out := &in.RegexMatchers, &out.RegexMatchers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationMatchers.
func (in *ApplicationMatchers) DeepCopy() *ApplicationMatchers {
	if in == nil {
		return nil
	}
	out := new(ApplicationMatchers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationsConfiguration) DeepCopyInto(out *ApplicationsConfiguration) {
	*out = *in
	in.Includes.DeepCopyInto(&out.Includes)
	in.Excludes.DeepCopyInto(&out.Excludes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationsConfiguration.
func (in *ApplicationsConfiguration) DeepCopy() *ApplicationsConfiguration {
	if in == nil {
		return nil
	}
	out := new(ApplicationsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfiguration) DeepCopyInto(out *ClusterConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfiguration.
func (in *ClusterConfiguration) DeepCopy() *ClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.Cluster = in.Cluster
	in.Applications.DeepCopyInto(&out.Applications)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Defaults) DeepCopyInto(out *Defaults) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]NameValuePair, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Defaults.
func (in *Defaults) DeepCopy() *Defaults {
	if in == nil {
		return nil
	}
	out := new(Defaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Destination) DeepCopyInto(out *Destination) {
	*out = *in
	out.Naming = in.Naming
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Destination.
func (in *Destination) DeepCopy() *Destination {
	if in == nil {
		return nil
	}
	out := new(Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisabledIteration) DeepCopyInto(out *DisabledIteration) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisabledIteration.
func (in *DisabledIteration) DeepCopy() *DisabledIteration {
	if in == nil {
		return nil
	}
	out := new(DisabledIteration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisabledIterationTarget) DeepCopyInto(out *DisabledIterationTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisabledIterationTarget.
func (in *DisabledIterationTarget) DeepCopy() *DisabledIterationTarget {
	if in == nil {
		return nil
	}
	out := new(DisabledIterationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisabledReconcile) DeepCopyInto(out *DisabledReconcile) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisabledReconcile.
func (in *DisabledReconcile) DeepCopy() *DisabledReconcile {
	if in == nil {
		return nil
	}
	out := new(DisabledReconcile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisabledReconcileTarget) DeepCopyInto(out *DisabledReconcileTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisabledReconcileTarget.
func (in *DisabledReconcileTarget) DeepCopy() *DisabledReconcileTarget {
	if in == nil {
		return nil
	}
	out := new(DisabledReconcileTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedIteration) DeepCopyInto(out *FailedIteration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedIteration.
func (in *FailedIteration) DeepCopy() *FailedIteration {
	if in == nil {
		return nil
	}
	out := new(FailedIteration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureStatus) DeepCopyInto(out *FailureStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureStatus.
func (in *FailureStatus) DeepCopy() *FailureStatus {
	if in == nil {
		return nil
	}
	out := new(FailureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxSource) DeepCopyInto(out *FluxSource) {
	*out = *in
	out.GitRepository = in.GitRepository
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxSource.
func (in *FluxSource) DeepCopy() *FluxSource {
	if in == nil {
		return nil
	}
	out := new(FluxSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxSourceGitRepository) DeepCopyInto(out *FluxSourceGitRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxSourceGitRepository.
func (in *FluxSourceGitRepository) DeepCopy() *FluxSourceGitRepository {
	if in == nil {
		return nil
	}
	out := new(FluxSourceGitRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Iteration) DeepCopyInto(out *Iteration) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]NameValuePair, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Iteration.
func (in *Iteration) DeepCopy() *Iteration {
	if in == nil {
		return nil
	}
	out := new(Iteration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Konfiguration) DeepCopyInto(out *Konfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Konfiguration.
func (in *Konfiguration) DeepCopy() *Konfiguration {
	if in == nil {
		return nil
	}
	out := new(Konfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Konfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationList) DeepCopyInto(out *KonfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Konfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationList.
func (in *KonfigurationList) DeepCopy() *KonfigurationList {
	if in == nil {
		return nil
	}
	out := new(KonfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationSchema) DeepCopyInto(out *KonfigurationSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationSchema.
func (in *KonfigurationSchema) DeepCopy() *KonfigurationSchema {
	if in == nil {
		return nil
	}
	out := new(KonfigurationSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfigurationSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationSchemaList) DeepCopyInto(out *KonfigurationSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfigurationSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationSchemaList.
func (in *KonfigurationSchemaList) DeepCopy() *KonfigurationSchemaList {
	if in == nil {
		return nil
	}
	out := new(KonfigurationSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfigurationSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationSchemaSpec) DeepCopyInto(out *KonfigurationSchemaSpec) {
	*out = *in
	out.Raw = in.Raw
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationSchemaSpec.
func (in *KonfigurationSchemaSpec) DeepCopy() *KonfigurationSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(KonfigurationSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationSchemaStatus) DeepCopyInto(out *KonfigurationSchemaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationSchemaStatus.
func (in *KonfigurationSchemaStatus) DeepCopy() *KonfigurationSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(KonfigurationSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationSpec) DeepCopyInto(out *KonfigurationSpec) {
	*out = *in
	in.Targets.DeepCopyInto(&out.Targets)
	out.Destination = in.Destination
	in.Reconciliation.DeepCopyInto(&out.Reconciliation)
	out.Sources = in.Sources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationSpec.
func (in *KonfigurationSpec) DeepCopy() *KonfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(KonfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfigurationStatus) DeepCopyInto(out *KonfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]FailedIteration, len(*in))
		copy(*out, *in)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = make([]DisabledIteration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfigurationStatus.
func (in *KonfigurationStatus) DeepCopy() *KonfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(KonfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfiguration) DeepCopyInto(out *ManagementClusterConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfiguration.
func (in *ManagementClusterConfiguration) DeepCopy() *ManagementClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfigurationList) DeepCopyInto(out *ManagementClusterConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementClusterConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfigurationList.
func (in *ManagementClusterConfigurationList) DeepCopy() *ManagementClusterConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfigurationSpec) DeepCopyInto(out *ManagementClusterConfigurationSpec) {
	*out = *in
	out.Sources = in.Sources
	out.Destination = in.Destination
	in.Configuration.DeepCopyInto(&out.Configuration)
	in.Reconciliation.DeepCopyInto(&out.Reconciliation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfigurationSpec.
func (in *ManagementClusterConfigurationSpec) DeepCopy() *ManagementClusterConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterConfigurationStatus) DeepCopyInto(out *ManagementClusterConfigurationStatus) {
	*out = *in
	if in.Failures != nil {
		in, out := &in.Failures, &out.Failures
		*out = make([]FailureStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Misses != nil {
		in, out := &in.Misses, &out.Misses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisabledReconciles != nil {
		in, out := &in.DisabledReconciles, &out.DisabledReconciles
		*out = make([]DisabledReconcile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterConfigurationStatus.
func (in *ManagementClusterConfigurationStatus) DeepCopy() *ManagementClusterConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameValuePair) DeepCopyInto(out *NameValuePair) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameValuePair.
func (in *NameValuePair) DeepCopy() *NameValuePair {
	if in == nil {
		return nil
	}
	out := new(NameValuePair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamingOptions) DeepCopyInto(out *NamingOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamingOptions.
func (in *NamingOptions) DeepCopy() *NamingOptions {
	if in == nil {
		return nil
	}
	out := new(NamingOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Raw) DeepCopyInto(out *Raw) {
	*out = *in
	out.Remote = in.Remote
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Raw.
func (in *Raw) DeepCopy() *Raw {
	if in == nil {
		return nil
	}
	out := new(Raw)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reconciliation) DeepCopyInto(out *Reconciliation) {
	*out = *in
	out.Interval = in.Interval
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reconciliation.
func (in *Reconciliation) DeepCopy() *Reconciliation {
	if in == nil {
		return nil
	}
	out := new(Reconciliation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Remote) DeepCopyInto(out *Remote) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Remote.
func (in *Remote) DeepCopy() *Remote {
	if in == nil {
		return nil
	}
	out := new(Remote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schema) DeepCopyInto(out *Schema) {
	*out = *in
	out.Reference = in.Reference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schema.
func (in *Schema) DeepCopy() *Schema {
	if in == nil {
		return nil
	}
	out := new(Schema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaReference) DeepCopyInto(out *SchemaReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaReference.
func (in *SchemaReference) DeepCopy() *SchemaReference {
	if in == nil {
		return nil
	}
	out := new(SchemaReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sources) DeepCopyInto(out *Sources) {
	*out = *in
	out.Flux = in.Flux
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sources.
func (in *Sources) DeepCopy() *Sources {
	if in == nil {
		return nil
	}
	out := new(Sources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Targets) DeepCopyInto(out *Targets) {
	*out = *in
	out.Schema = in.Schema
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Iterations != nil {
		in, out := &in.Iterations, &out.Iterations
		*out = make(map[string]Iteration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Targets.
func (in *Targets) DeepCopy() *Targets {
	if in == nil {
		return nil
	}
	out := new(Targets)
	in.DeepCopyInto(out)
	return out
}
