---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Release.Name }}-editor-role
rules:
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurations
  - konfigurationschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfigure.giantswarm.io
  resources:
  - konfigurations/status
  - konfigurationschemas/status
  verbs:
  - get
